/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.text.AbstractDocument;
import org.w3c.dom.css.RGBColor;
import vista.views.*;


/**
 *
 * @author kevin
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Dashboard() {
        initComponents();
        InitStyles();//Con este metodo llamamos a los estilos que usaremos para cada componente.botones, label, etc
        InitContent();
    }
    
    
    private void InitStyles(){
        menuTituloLB.putClientProperty("FlatLaf.style", "font: bold $h1.regular.font");
        menuTituloLB.setForeground(Color.BLACK);
        
        origenLB.putClientProperty("FlatLaf.style", "font: bold $h2.regular.font");
        origenLB.setForeground(Color.gray);
        destinoLB.putClientProperty("FlatLaf.style", "font: bold $h2.regular.font");
        destinoLB.setForeground(Color.gray);
        
        fechasLB.putClientProperty("FlatLaf.style", "font: bold $h2.regular.font");
        fechasLB.setForeground(Color.gray);
        salidaLB.putClientProperty("FlatLaf.style", "font: bold $h3.regular.font");
        salidaLB.setForeground(Color.LIGHT_GRAY);
        regresoLB.putClientProperty("FlatLaf.style", "font: bold $h3.regular.font");
        regresoLB.setForeground(Color.LIGHT_GRAY);


    }
    private void InitContent(){
        ShowPanel(new Bienvenida());
    }
    public void ShowPanel(JPanel p){
        p.setSize(883, 650);
        p.setLocation(0,0);
       
        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        logoLB = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        menuTituloLB = new javax.swing.JLabel();
        origenCB = new javax.swing.JComboBox<>();
        origenLB = new javax.swing.JLabel();
        destinoLB = new javax.swing.JLabel();
        destinoCB = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        buscarBTN = new javax.swing.JButton();
        fechasLB = new javax.swing.JLabel();
        fechaSalidaFT = new javax.swing.JFormattedTextField();
        salidaLB = new javax.swing.JLabel();
        regresoLB = new javax.swing.JLabel();
        fechaRegresoFT = new javax.swing.JFormattedTextField();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));

        Background.setBackground(new java.awt.Color(0, 43, 92));
        Background.setMinimumSize(new java.awt.Dimension(1280, 720));
        Background.setPreferredSize(new java.awt.Dimension(1920, 1080));

        header.setBackground(new java.awt.Color(11, 35, 67));

        logoLB.setIcon(new javax.swing.ImageIcon("C:\\Users\\kevin\\Documents\\workspace\\patrones-de-disenio\\Hoteles_Vuelos_Grupal\\src\\main\\java\\vista\\recursos\\logo40px.png")); // NOI18N

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(logoLB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(logoLB)
                .addGap(14, 14, 14))
        );

        menu.setBackground(new java.awt.Color(255, 255, 255));

        menuTituloLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuTituloLB.setText("RESERVA TU VUELO");
        menuTituloLB.setToolTipText("");

        origenCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quito", "Guayakill", "Lima", "Cartagena", "Buenos Aires", "Barcelona", "Rio de Janeiro", "Santiago", "Ciudad de México" }));
        origenCB.setToolTipText("asd");

        origenLB.setText("Origen");

        destinoLB.setText("Destino");

        destinoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guayakill", "Quito", "Lima", "Cartagena", "Buenos Aires", "Barcelona", "Rio de Janeiro", "Santiago", "Ciudad de México" }));
        destinoCB.setToolTipText("asd");

        buscarBTN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buscarBTN.setForeground(new java.awt.Color(51, 51, 51));
        buscarBTN.setIcon(new javax.swing.ImageIcon("C:\\Users\\kevin\\Documents\\workspace\\patrones-de-disenio\\Hoteles_Vuelos_Grupal\\src\\main\\java\\vista\\recursos\\iconoBuscar24px.png")); // NOI18N
        buscarBTN.setText("Buscar Vuelos");
        buscarBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBTNActionPerformed(evt);
            }
        });

        fechasLB.setText("Fechas");

        fechaSalidaFT.setForeground(new java.awt.Color(102, 102, 102));
        fechaSalidaFT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/MM/y"))));
        fechaSalidaFT.setText("DD/MM/YYYY");
        fechaSalidaFT.setToolTipText("");
        fechaSalidaFT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaSalidaFTActionPerformed(evt);
            }
        });

        salidaLB.setText("Salida");

        regresoLB.setText("Regreso");

        fechaRegresoFT.setForeground(new java.awt.Color(102, 102, 102));
        fechaRegresoFT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/MM/y"))));
        fechaRegresoFT.setText("DD/MM/YYYY");
        fechaRegresoFT.setToolTipText("");
        fechaRegresoFT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaRegresoFTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuTituloLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buscarBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 43, Short.MAX_VALUE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(origenLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(origenCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(destinoLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(destinoCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fechasLB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salidaLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(regresoLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(fechaSalidaFT, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(menuLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(fechaRegresoFT, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(menuTituloLB, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(origenLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(origenCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(destinoLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(destinoCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(fechasLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salidaLB)
                .addGap(9, 9, 9)
                .addComponent(fechaSalidaFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(regresoLB)
                .addGap(9, 9, 9)
                .addComponent(fechaRegresoFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(buscarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );

        content.setBackground(new java.awt.Color(0, 73, 144));
        content.setPreferredSize(new java.awt.Dimension(883, 20));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 883, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(header, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBTNActionPerformed
        ShowPanel(new Principal());
    }//GEN-LAST:event_buscarBTNActionPerformed

    private void fechaSalidaFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaSalidaFTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaSalidaFTActionPerformed

    private void fechaRegresoFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaRegresoFTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaRegresoFTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMaterialLighterIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton buscarBTN;
    private javax.swing.JPanel content;
    private javax.swing.JComboBox<String> destinoCB;
    private javax.swing.JLabel destinoLB;
    private javax.swing.JFormattedTextField fechaRegresoFT;
    private javax.swing.JFormattedTextField fechaSalidaFT;
    private javax.swing.JLabel fechasLB;
    private javax.swing.JPanel header;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logoLB;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel menuTituloLB;
    private javax.swing.JComboBox<String> origenCB;
    private javax.swing.JLabel origenLB;
    private javax.swing.JLabel regresoLB;
    private javax.swing.JLabel salidaLB;
    // End of variables declaration//GEN-END:variables
}
